
package pack.pkg7;
import org.json.JSONArray;
import org.json.JSONObject;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import pack.pkg7.InstructorService;

/**
 *
 * @author Hannah Emad
 */
public class DeleteCourse extends javax.swing.JFrame {

   private final CourseJsonDB courseDB = new CourseJsonDB();
   
    public DeleteCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//private void viewCourse() {
      //  String courseId = courseIdField.getText().trim();

        if (courseId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Course ID!");
            return;
        }
        int x=0;
        try {
            //JSONArray Courses = InstructorService.editCourse(courseId, String newTitle, String newDescription);
            // System.out.println(students.length());
           // System.out.println("Students raw: " + students);
           JSONArray Courses = courseDB.loadCourses();

            TableModel.setRowCount(0);
            //x = students.length();
            for (int i = 0; i < Courses.length(); i++) {
                JSONObject s = Courses.getJSONObject(i);
                tableModel.addRow(new Object[]{
                    s.getString("description"),
                    s.getString("students"),
                    s.getString("title"),
                    s.getString("courseId"),
                    s.getString("instructorId"),
                    s.getString("courseId")
                });
            }

        } catch (Exception ex) {
          //  System.out.println(x);
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
               // new DeleteCourse().setVisible(true);
      //      }
        //});
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
