package pack.pkg7;

import org.json.JSONArray;
import org.json.JSONObject;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;

public class EditCourse extends javax.swing.JFrame {
  private final CourseJsonDB courseDB = new CourseJsonDB();
  private Instructor instructor;

    private JTextField courseIdField;
    private JButton viewBtn;
    private JTable studentTable;
    private DefaultTableModel tableModel;

    public EditCourse( Instructor i,InstructorService Parent) {
        this.instructor = i;
        //this.instructorService = service;
        setLayout(null);

        JLabel lblCourseId = new JLabel("Course ID:");
        lblCourseId.setBounds(20, 20, 100, 25);
        add(lblCourseId);

        courseIdField = new JTextField();
        courseIdField.setBounds(120, 20, 250, 25);
        add(courseIdField);

        viewBtn = new JButton("View Courses");
        viewBtn.setBounds(380, 20, 150, 25);
        add(viewBtn);

        //
        tableModel = new DefaultTableModel(new Object[]{"Student ID", "Student Name", "Email"}, 0);
        jTable2.setModel(tableModel);
        JScrollPane sp = new JScrollPane(jTable2);
        sp.setBounds(20, 70, 510, 200);
        add(sp);

        viewBtn.addActionListener((ActionEvent e) -> viewCourses());
    }
    public EditCourse(Instructor inst,InstructorFrontend parent) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CourseID", "Name", "Description"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRowIndex = jTable2.getSelectedRow();
        
        if (selectedRowIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to edit!", "No Row Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Object courseIdObject = jTable2.getModel().getValueAt(selectedRowIndex, 0);
        String courseId = courseIdObject.toString();
        
        // Example: Assuming Course Title is in column 2 (index 2)
        Object courseTitleObject = jTable2.getModel().getValueAt(selectedRowIndex, 1);
        String courseTitle = courseTitleObject.toString();
        

        // 3. Display the extracted values (for testing)
        JOptionPane.showMessageDialog(this, 
            "Selected Course ID: " + courseId + "\n" +
            "Selected Course Title: " + courseTitle,
            "Course Selected", JOptionPane.INFORMATION_MESSAGE);
        
        // *** TODO: Add logic here to open an edit dialog/form ***
        // E.g., new EditCourseDetailsForm(courseId, courseTitle).setVisible(true);

 
       
        
    }//GEN-LAST:event_jButton1ActionPerformed
 private void viewCourses() {
//        String courseId = courseIdField.getText().trim();
//
//        if (courseId.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Please enter a Course ID!");
//            return;
//        }
//        int x=0;
        try {
            //JSONArray Courses = InstructorService.editCourse(courseId, String newTitle, String newDescription);
            // System.out.println(students.length());
           // System.out.println("Students raw: " + students);
           JSONArray Courses = courseDB.loadCourses();

            tableModel.setRowCount(0);
            //x = students.length();
            for (int i = 0; i < Courses.length(); i++) {
                JSONObject s = Courses.getJSONObject(i);
                tableModel.addRow(new Object[]{
                    s.getString("description"),
                    s.getString("students"),
                    s.getString("title"),
                    s.getString("courseId"),
                    s.getString("instructorId"),
                    s.getString("courseId")
                });
            }

        } catch (Exception ex) {
          //  System.out.println(x);
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
 }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditCourse().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
