package pack.pkg7;

import org.json.JSONArray;
import org.json.JSONObject;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import pack.pkg7.InstructorService;

public class ViewEnrolledStudent extends javax.swing.JFrame {

    private InstructorService instructorService;

    private JTextField courseIdField;
    private JButton viewBtn;
    private JTable studentTable;
    private DefaultTableModel tableModel;

    public ViewEnrolledStudent( InstructorService i) {
        this.instructorService = i;
        //this.instructorService = service;
        setLayout(null);

        JLabel lblCourseId = new JLabel("Course ID:");
        lblCourseId.setBounds(20, 20, 100, 25);
        add(lblCourseId);

        courseIdField = new JTextField();
        courseIdField.setBounds(120, 20, 250, 25);
        add(courseIdField);

        viewBtn = new JButton("View Students");
        viewBtn.setBounds(380, 20, 150, 25);
        add(viewBtn);

        //
        tableModel = new DefaultTableModel(new Object[]{"Student ID", "Student Name", "Email"}, 0);
        studentTable = new JTable(tableModel);
        JScrollPane sp = new JScrollPane(studentTable);
        sp.setBounds(20, 70, 510, 200);
        add(sp);

        viewBtn.addActionListener((ActionEvent e) -> viewStudents());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student Id", "name", "email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewStudents() {
        String courseId = courseIdField.getText().trim();

        if (courseId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Course ID!");
            return;
        }
        int x=0;
        try {
            JSONArray students = instructorService.ViewEnrolledStudents(courseId);
            // System.out.println(students.length());
           // System.out.println("Students raw: " + students);

            tableModel.setRowCount(0);
            //x = students.length();
            for (int i = 0; i < students.length(); i++) {
                JSONObject s = students.getJSONObject(i);
                tableModel.addRow(new Object[]{
                    s.getString("userId"),
                    s.getString("username"),
                    s.getString("email")
                });
            }

        } catch (Exception ex) {
          //  System.out.println(x);
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
